# ================================================================================
# Jobs API
#
# Handles CRUD operations for job scoring objects.
#
# Design
# - Job metadata stored in DynamoDB
# - Job-owned text artifacts stored in S3 at deterministic paths
# - Resume snapshot stored in S3 at job creation
# - Job description stored in S3 when provided as raw text or later by AI
# - Job analysis stored in S3 when generated by AI
# - Notes stored in S3 and are the only mutable field
#
# DynamoDB Keys
#   pk = USER#<user_id>
#   sk = JOB#<job_id>
#
# S3 Layout
#   users/USER#<user_id>/jobs/JOB#<job_id>/resume_snapshot.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/job_description.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/job_analysis.txt
#   users/USER#<user_id>/jobs/JOB#<job_id>/notes.txt
# ================================================================================

import json
import os
import uuid
from datetime import datetime, timezone
from decimal import Decimal

import boto3
from boto3.dynamodb.conditions import Key
from botocore.exceptions import ClientError

# ------------------------------------------------------------------------------
# AWS clients
# ------------------------------------------------------------------------------

table = boto3.resource("dynamodb").Table(os.environ["TABLE_NAME"])
s3 = boto3.client("s3")
sqs = boto3.client("sqs")

BACKEND_BUCKET = os.environ["BACKEND_BUCKET_NAME"]
JOB_QUEUE_URL = os.environ["JOB_QUEUE_URL"]


# ------------------------------------------------------------------------------
# Common helpers
# ------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Function: utc_now
#
# Purpose
# Returns the current UTC timestamp in ISO 8601 format, truncated to
# second precision.
#
# Returns
# - ISO 8601 timestamp string (no microseconds)
# --------------------------------------------------------------------------------
def utc_now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def json_serializer(value):
    """
    Convert DynamoDB Decimal values into standard JSON numeric types.

    Notes
    - boto3 returns DynamoDB numbers as Decimal
    - json.dumps() cannot serialize Decimal by default
    - Whole numbers are returned as int
    - Fractional numbers are returned as float
    """

    if isinstance(value, Decimal):
        if value % 1 == 0:
            return int(value)

        return float(value)

    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


# --------------------------------------------------------------------------------
# Function: response
#
# Purpose
# Builds a standard API Gateway response dict. Uses json_serializer to
# handle DynamoDB Decimal values in the response body.
#
# Arguments
# - code : HTTP status code integer
# - body : Python object to serialize as the JSON response body
#
# Returns
# - dict with statusCode and body keys
# --------------------------------------------------------------------------------
def response(code, body):
    return {
        "statusCode": code,
        "body": json.dumps(body, default=json_serializer)
    }


# --------------------------------------------------------------------------------
# Function: get_user_id
#
# Purpose
# Extracts the authenticated user ID from the Cognito JWT claims on
# the API Gateway event.
#
# Arguments
# - event : API Gateway Lambda event dict
#
# Returns
# - cognito:username, sub, or "demo" as fallback
# --------------------------------------------------------------------------------
def get_user_id(event):
    claims = (
        event.get("requestContext", {})
        .get("authorizer", {})
        .get("jwt", {})
        .get("claims", {})
    )

    return claims.get("cognito:username") or claims.get("sub") or "demo"


# --------------------------------------------------------------------------------
# Function: get_job_id
#
# Purpose
# Extracts the job_id path parameter from the API Gateway event.
#
# Arguments
# - event : API Gateway Lambda event dict
#
# Returns
# - job_id string or None if not present
# --------------------------------------------------------------------------------
def get_job_id(event):
    path = event.get("pathParameters") or {}
    return path.get("job_id")


# --------------------------------------------------------------------------------
# Function: build_job_paths
#
# Purpose
# Derives DynamoDB keys and all S3 object paths for a given user/job pair.
#
# Arguments
# - user_id : authenticated user identifier
# - job_id  : UUID of the job record
#
# Returns
# - dict with pk, sk, base path, and per-artifact S3 keys
# --------------------------------------------------------------------------------
def build_job_paths(user_id, job_id):

    pk = f"USER#{user_id}"
    sk = f"JOB#{job_id}"

    base = f"users/{pk}/jobs/{sk}"

    return {
        "pk": pk,
        "sk": sk,
        "base": base,
        "resume_snapshot_key": f"{base}/resume_snapshot.txt",
        "job_description_key": f"{base}/job_description.txt",
        "job_analysis_key": f"{base}/job_analysis.txt",
        "notes_key": f"{base}/notes.txt"
    }


# --------------------------------------------------------------------------------
# Function: get_resume_item
#
# Purpose
# Fetches a resume record from DynamoDB for the given user.
#
# Arguments
# - user_id   : authenticated user identifier
# - resume_id : UUID of the resume record
#
# Returns
# - DynamoDB item dict or None if not found
# --------------------------------------------------------------------------------
def get_resume_item(user_id, resume_id):

    pk = f"USER#{user_id}"
    sk = f"RESUME#{resume_id}"

    result = table.get_item(
        Key={
            "pk": pk,
            "sk": sk
        }
    )

    return result.get("Item")


# --------------------------------------------------------------------------------
# Function: get_job_item
#
# Purpose
# Fetches a job record from DynamoDB for the given user.
#
# Arguments
# - user_id : authenticated user identifier
# - job_id  : UUID of the job record
#
# Returns
# - DynamoDB item dict or None if not found
# --------------------------------------------------------------------------------
def get_job_item(user_id, job_id):

    pk = f"USER#{user_id}"
    sk = f"JOB#{job_id}"

    result = table.get_item(
        Key={
            "pk": pk,
            "sk": sk
        }
    )

    return result.get("Item")


# --------------------------------------------------------------------------------
# Function: write_s3_text
#
# Purpose
# Writes a UTF-8 encoded text string to the backend S3 bucket.
#
# Arguments
# - key  : S3 object key
# - text : string content to write
# --------------------------------------------------------------------------------
def write_s3_text(key, text):

    s3.put_object(
        Bucket=BACKEND_BUCKET,
        Key=key,
        Body=text.encode("utf-8"),
        ContentType="text/plain"
    )


# --------------------------------------------------------------------------------
# Function: read_s3_text
#
# Purpose
# Reads a UTF-8 text object from the backend S3 bucket. Returns an
# empty string if the object does not exist (NoSuchKey / 404).
#
# Arguments
# - key : S3 object key
#
# Returns
# - object contents as string, or empty string if missing
# --------------------------------------------------------------------------------
def read_s3_text(key):

    try:
        result = s3.get_object(
            Bucket=BACKEND_BUCKET,
            Key=key
        )
        return result["Body"].read().decode("utf-8")
    except ClientError as exc:
        error_code = exc.response.get("Error", {}).get("Code")

        if error_code in ["NoSuchKey", "404"]:
            return ""

        raise


# --------------------------------------------------------------------------------
# Function: delete_s3_object
#
# Purpose
# Deletes an object from the backend S3 bucket. No-ops for empty keys.
#
# Arguments
# - key : S3 object key to delete
# --------------------------------------------------------------------------------
def delete_s3_object(key):

    if not key:
        return

    s3.delete_object(
        Bucket=BACKEND_BUCKET,
        Key=key
    )


# --------------------------------------------------------------------------------
# Function: enqueue_job_request
#
# Purpose
# Sends a scoring request message to the SQS job queue.
#
# Arguments
# - user_id     : authenticated user identifier
# - job_id      : UUID of the job record
# - resume_id   : UUID of the resume to score against
# - source_type : "url" or "raw_text"
# - job_url     : URL to fetch for URL-type jobs, empty string otherwise
# --------------------------------------------------------------------------------
def enqueue_job_request(user_id, job_id, resume_id, source_type, job_url):
    message = {
        "user_id": user_id,
        "job_id": job_id,
        "resume_id": resume_id,
        "source_type": source_type,
        "job_url": job_url
    }

    sqs.send_message(
        QueueUrl=JOB_QUEUE_URL,
        MessageBody=json.dumps(message)
    )


# ------------------------------------------------------------------------------
# POST /jobs
#
# Creates a job scoring record.
# ------------------------------------------------------------------------------

def create_job(event):

    user_id = get_user_id(event)
    body = json.loads(event["body"])

    resume_id = body.get("resume_id", "").strip()
    source_type = body.get("source_type", "").strip()
    job_url = body.get("job_url", "").strip()
    job_description = body.get("job_description", "").strip()
    notes = body.get("notes", "").strip()

    if not resume_id:
        return response(400, {"error": "resume_id is required"})

    if source_type not in ["url", "raw_text"]:
        return response(
            400,
            {"error": "source_type must be 'url' or 'raw_text'"}
        )

    if source_type == "url" and not job_url:
        return response(400, {"error": "job_url is required"})

    if source_type == "raw_text" and not job_description:
        return response(400, {"error": "job_description is required"})

    # --------------------------------------------------------------------------
    # Validate resume exists
    # --------------------------------------------------------------------------

    resume_item = get_resume_item(user_id, resume_id)

    if not resume_item:
        return response(404, {"error": "resume not found"})

    resume_s3_key = resume_item["s3_key"]

    # --------------------------------------------------------------------------
    # Create job identifiers and paths
    # --------------------------------------------------------------------------

    job_id = str(uuid.uuid4())
    paths = build_job_paths(user_id, job_id)
    now = utc_now()

    # --------------------------------------------------------------------------
    # Copy resume snapshot into job folder
    # --------------------------------------------------------------------------

    resume_object = s3.get_object(
        Bucket=BACKEND_BUCKET,
        Key=resume_s3_key
    )

    resume_text = resume_object["Body"].read()

    s3.put_object(
        Bucket=BACKEND_BUCKET,
        Key=paths["resume_snapshot_key"],
        Body=resume_text,
        ContentType="text/plain"
    )

    # --------------------------------------------------------------------------
    # Store job description when provided as raw text
    # --------------------------------------------------------------------------

    if source_type == "raw_text":
        write_s3_text(paths["job_description_key"], job_description)

    # --------------------------------------------------------------------------
    # Store notes when provided
    # --------------------------------------------------------------------------

    if notes:
        write_s3_text(paths["notes_key"], notes)

    # --------------------------------------------------------------------------
    # Write metadata
    # --------------------------------------------------------------------------

    table.put_item(
        Item={
            "pk": paths["pk"],
            "sk": paths["sk"],
            "resume_id": resume_id,
            "source_type": source_type,
            "job_url": job_url if source_type == "url" else "",
            "status": "submitted",
            "status_message": "Job submitted for scoring",
            "job_title": "",
            "company": "",
            "score": None,
            "created_at": now,
            "updated_at": now
        }
    )

    # --------------------------------------------------------------------------
    # Enqueue scoring request
    # --------------------------------------------------------------------------

    try:
        enqueue_job_request(
            user_id=user_id,
            job_id=job_id,
            resume_id=resume_id,
            source_type=source_type,
            job_url=job_url if source_type == "url" else ""
        )
    except ClientError as exc:
        table.update_item(
            Key={
                "pk": paths["pk"],
                "sk": paths["sk"]
            },
            UpdateExpression=(
                "SET #status = :status, "
                "status_message = :status_message, "
                "updated_at = :updated_at"
            ),
            ExpressionAttributeNames={
                "#status": "status"
            },
            ExpressionAttributeValues={
                ":status": "queue_error",
                ":status_message": "Failed to enqueue scoring request",
                ":updated_at": utc_now()
            }
        )

        return response(
            500,
            {
                "error": "failed to enqueue scoring request",
                "details": str(exc)
            }
        )

    return response(
        200,
        {
            "job_id": job_id,
            "status": "submitted",
            "status_message": "Job submitted for scoring"
        }
    )


# ------------------------------------------------------------------------------
# GET /jobs
#
# Returns job metadata for the current user.
# ------------------------------------------------------------------------------

def list_jobs(event=None):

    user_id = get_user_id(event or {})
    pk = f"USER#{user_id}"

    result = table.query(
        KeyConditionExpression=Key("pk").eq(pk)
    )

    jobs = [
        {
            "job_id": item["sk"].replace("JOB#", "", 1),
            "resume_id": item.get("resume_id"),
            "status": item.get("status"),
            "status_message": item.get("status_message"),
            "job_title": item.get("job_title"),
            "company": item.get("company"),
            "score": item.get("score"),
            "created_at": item.get("created_at"),
            "updated_at": item.get("updated_at")
        }
        for item in result.get("Items", [])
        if item["sk"].startswith("JOB#")
    ]

    return response(200, jobs)


# ------------------------------------------------------------------------------
# GET /jobs/{job_id}
#
# Returns job metadata and job-owned text artifacts.
# ------------------------------------------------------------------------------

def get_job(event):

    user_id = get_user_id(event)
    job_id = get_job_id(event)

    if not job_id:
        return response(400, {"error": "job_id is required"})

    item = get_job_item(user_id, job_id)

    if not item:
        return response(404, {"error": "job not found"})

    paths = build_job_paths(user_id, job_id)

    resume_snapshot_text = read_s3_text(paths["resume_snapshot_key"])
    job_description_text = read_s3_text(paths["job_description_key"])
    job_analysis_text = read_s3_text(paths["job_analysis_key"])
    notes_text = read_s3_text(paths["notes_key"])

    return response(
        200,
        {
            "job_id": job_id,
            "resume_id": item.get("resume_id"),
            "source_type": item.get("source_type"),
            "job_url": item.get("job_url"),
            "status": item.get("status"),
            "status_message": item.get("status_message"),
            "job_title": item.get("job_title", ""),
            "company": item.get("company", ""),
            "score": item.get("score"),
            "resume_snapshot": resume_snapshot_text,
            "job_description": job_description_text,
            "job_analysis": job_analysis_text,
            "notes": notes_text,
            "created_at": item.get("created_at"),
            "updated_at": item.get("updated_at")
        }
    )


# ------------------------------------------------------------------------------
# PATCH /jobs/{job_id}/notes
#
# Updates notes only. All other job fields are immutable.
# ------------------------------------------------------------------------------

def update_job_notes(event):

    user_id = get_user_id(event)
    job_id = get_job_id(event)

    if not job_id:
        return response(400, {"error": "job_id is required"})

    body = json.loads(event["body"])
    notes = body.get("notes", "").strip()

    item = get_job_item(user_id, job_id)

    if not item:
        return response(404, {"error": "job not found"})

    paths = build_job_paths(user_id, job_id)

    if notes:
        write_s3_text(paths["notes_key"], notes)
    else:
        delete_s3_object(paths["notes_key"])

    table.update_item(
        Key={
            "pk": paths["pk"],
            "sk": paths["sk"]
        },
        UpdateExpression="SET updated_at = :updated_at",
        ExpressionAttributeValues={
            ":updated_at": utc_now()
        }
    )

    return response(200, {"updated": True})


# ------------------------------------------------------------------------------
# DELETE /jobs/{job_id}
#
# Deletes job metadata and all job-owned S3 objects.
# ------------------------------------------------------------------------------

def delete_job(event):

    user_id = get_user_id(event)
    job_id = get_job_id(event)

    if not job_id:
        return response(400, {"error": "job_id is required"})

    item = get_job_item(user_id, job_id)

    if not item:
        return response(404, {"error": "job not found"})

    paths = build_job_paths(user_id, job_id)

    delete_s3_object(paths["resume_snapshot_key"])
    delete_s3_object(paths["job_description_key"])
    delete_s3_object(paths["job_analysis_key"])
    delete_s3_object(paths["notes_key"])

    table.delete_item(
        Key={
            "pk": paths["pk"],
            "sk": paths["sk"]
        }
    )

    return response(200, {"deleted": True})